version: "3.8"

services:
  app:
    build: .
    container_name: patient-api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    command: bash -c "sleep 30 && npm run dev"
    networks:
      - mynetwork

  email-consumer:
    build: .
    container_name: email-consumer
    depends_on:
      - activemq
    command: bash -c "sleep 35 && npx ts-node src/consumers/email-consumer.ts"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - mynetwork

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    tmpfs:
      - /var/lib/mysql
    networks:
      - mynetwork

  activemq:
    image: rmohr/activemq
    platform: linux/amd64
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./activemq-no-persistence.xml:/opt/activemq/conf/activemq.xml
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge